server:
  port: 8081
spring:
  datasource:
    url: ENC(Pak3VxuYgko+IDuuC+sOZ49Rb9ffPpVZDGOxkM1rbZkqNlz7aPQ2zXRaDOYJrdisnFuOoPQ+xZ6bIAQyfM1TqJtJ00TIUxYhMV6yKQzZ4mU=)
    username: ENC(fj2qWIkXfaWWM8+03trMMQ==)
    password: ENC(STlkaVosBUfrvSi8nD6q1Ric/IbcdPB1)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false
  logging:
    level:
      root: TRACE

cloud:
  aws:
    s3:
      bucket: ENC(fkDPl+7g2CPGjwFoTNaslZTKPA1wOt26)
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      accessKey: ENC(1XV3KZpZja8KjHUcsqLdMjy1LSm+TTy+ClgWLlBfoMU=)
      secretKey: ENC(+SB5pLFPtT3ptsNG2vjotwu6mWyLkUo0jnQhcHzLTrqU0yRaU84Ylfi6rEvxLte+RZg5bvzu628=)
    stack:
      auto: false


jwt:
  secretKey: ENC(KBKVFcXoXDRLNYxe0GUTtDUQlsNFvZckn0TT3WjJYjhCNYV++LsvWp7qMvQNIGGk+pO/16Ty/CAwgLB3WRV5ivIo8po2O8HFhyLWtmdlvUrvb8iA8EFgcjgOlfgh5LIW)
  accessExpiration : 18000
  refreshExpiration: 25000

security:
  token:
    blacklistExpiration: 3600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


