server:
  port: 8081
spring:
  datasource:
    url: ENC(9pf2sV3TZZu23G5HqY4qbLoZrmIh6I3FtTTZs9fmcpSOiitzy3FL1hHfIq/akZl8XWqJnZB19imSzjeDPgRsDG++7pOy43A6mofATTdrhwU=)
    username: ENC(p/sE16p/2JXHBAqS+cS5tA==)
    password: ENC(ygLeVXN000QWMoyRfn8HgjAUo7oFNBe1)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false
  logging:
    level:
      root: TRACE



jwt:
  secretKey: ENC(3O+Smw5/GYROTRFTd39aAq90ozu/bAYAoxM5fZ2pBCnM8Wj4QLDZlMfRoqYiFfaCnfHpes8gCe+EgojnAjH7ZTN6Ce5VQIoleSyqnea2MBFFlCfFkHM/iFJT1eJhuuDt)
  accessExpiration : 18000
  refreshExpiration: 25000

security:
  token:
    blacklistExpiration: 3600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor