openapi:
  key: 4068c6df2e2747388f427f22ff430b2d
server:
  port: 8081
spring:
  datasource:
    url: ENC(Qe7gGSLROlTRtl+ybrHQnVW+Mu41MrYb1zqVJWtcALlgZIkIwG6drU5OuJ8TkFr1TC1EPA+jATfAmNmTyDpIVGO9VOzh/mDSH1CSEQmpptQ=)
    username: ENC(4dL5K24+YsCQeLBYyfMQgA==)
    password: ENC(5FOLe5lOHvD74vZoQeR/OMNHWHcaSWb4)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false
  logging:
    level:
      root: TRACE

# cloud:
#   aws:
#     s3:
#       bucket: ENC(ZTyWwtnwg44/eTlxM9dKm29RKv6IoRR2)
#     region:
#       auto: false
#       static: ap-northeast-2
#     credentials:
#       accessKey: ENC(Ii8IlGMFA/1Lfu5IFZjyEEB9xb/Pc8kqjDO2H9tEKGg=)
#       secretKey: ENC(IvVQW8tX9rSM0HmRsi/Kc7ADB07XX5+F6qIxzGoepxYvb4M0jFElk+Bi1CMZFZGV/qs4Wnr7Ez0=)
#       auto: false
#     stack:


jwt:
  secretKey: ENC(3Dp2iazvSEd1MXpoaqPmuD5IcHvxNUjLa+uaJWgKlFDf2iiuOEDBg/e+p8nwUiEUHmxD7zpBbbWrXBN1eCBI43w+MsYhubgOZ2gL+uN6la0EHNFrSaneupbD7y5ZJAnV)
  accessExpiration : 1800000
  refreshExpiration: 2500000

security:
  token:
    blacklistExpiration: 3600000
  oauth2:
    client:
      registration:
        kakao:
          client-id: ENC(jBg067enz76zRIXaBDeyHp2XjhA/Fg1L9FZmPGpvc3iTTLFterzhk8gRT42XzHAZ)
          redirect-uri : ENC(mCkKTsCu5iqB+Sxwah+MUzqFfsfJB2MRdrCJIW8DK0FaYJHxBPwkeHhTWZKztQP2)
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          client-name: Kakao
          scope: account_email, profile_nickname
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
