server:
  port: 8081
spring:
  datasource:
    url: ENC(vZSHyMGk+GAdlKl29GX0V2BTBM4xRgdesz38syknA/CXFQf9IRTA3c6eDYuBcSybpxHof6VINDwBO9bhYdG/8plv2kSKhQXMvRmlhMapSEc=)
    username: ENC(vHFDTivxX0/t5D9Ado7l+w==)
    password: ENC(WaevxnAkf4D7ks9YsK9k4lShPfCHpabR)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false
  logging:
    level:
      root: TRACE

cloud:
  aws:
    s3:
      bucket: ENC(1CJTkRAzAWDFgtEvHQVPhBx16Ge/Z29V)
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      accessKey: ENC(mPCt6tx7q2O1tLtbeiiAK3HNcxkYygk5qjcB+aqQnIE=)
      secretKey: ENC(nOqtWOp3rf3iM54Os7LW5OM1UA9Bzl4cbyRN7cEP2XvZH4xY1BgJnqmPD8AkEMSDZFPKh9Ic8TY=)
      auto: false
    stack:


jwt:
  secretKey: ENC(6Liyr+shDhDepUJ2cYem43YyLcHgmQl+TGW28psR+NH5evfBYgZRrddd5seoVqTIf4hu4gwPLjCnArQb1akOVYiLBbLkIiPh8ZmZmgFptLiXBHWFBC4JH8shqDwoD4RJ)
  accessExpiration : 18000
  refreshExpiration: 25000

security:
  token:
    blacklistExpiration: 3600000
  oauth2:
    client:
      registration:
        kakao:
          client-id: ENC(KXs4zdTw7+/uFJoB66QfzYaXpul/17coD+Tr+fLfZYoUzUbvqIakpbj4Wjbf7L41)
          redirect-uri : ENC(+BrpHEarr0VQ9W8opYCItVi7rjouOMyspADlXszCxM6TK81fLvsJBbk13PxinbsmWt+YrsGAeHlRZvx/Zrp7Pg==)
          authorization-grant-type: authorization_code
          client-authentication-method: POST
          client-name: Kakao
          scope: profile_nickname
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
