server:
  port: 8081
spring:
  datasource:
    url: ENC(NOd6PoXkT+0LcpFrlm5XzBQPIbTW3vQrfXVpQHunZseo6+GENOx+c2Joza+mizaiRg+qK8a+NCrTsBvcgX2+Er2Qcb1W/mokHYutpxOZkEc=)
    username: ENC(KDsj2LZoAhbXNLpX9xt5CA==)
    password: ENC(+e4oL8vuZV0rLrTPP489bai4wWo8K/qM)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false
  logging:
    level:
      root: TRACE



jwt:
  secretKey: ENC(+XiHm49foxIHp53nDaSgrM2PlT7LcBIIrlLe+EfDNVJ5SPg3LENEyMhJoxO0nYUU2ZqqYNNQS9OYl4DgUXHCfXda5Yb8DJ9ZyLzo9XvUar6cKuzbK2Y3Y+ToxRupje07)
  accessExpiration : 18000
  refreshExpiration: 25000

security:
  token:
    blacklistExpiration: 3600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor