server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swsback
    username: root
    password: 123456
#    url: ENC(KcZfiyL7xhIPYbr6Hjr2TFgPCe+loiQCoONsbe/TaB5G2DBlkCfyjIg7G+pA/VKE+NYRz55yxzspNajEDgh8aKdFMEl8yn/Ck+mXvj29lPE=)
#    username: ENC(aVLZkl4iHCPJai7ySPLacw==)
#    password: ENC(G3qoBrFWJLais1SByH2kLD16k5pulMPg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false
  logging:
    level:
      root: TRACE



jwt:
  secretKey: gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767
  #  secretKey: ENC(E2ngNWl5evNIbF856CLqAEcgtM5Xrv9DQjFAn9RnSVYNCxNXgNIO9Gw6mwESKwnPgd6cInFnT4qcpl2L0NKVRIeqpuDvlATsyCw2PPoiisOMNH+9q3TTCLUrO2VtDxiK)
  accessExpiration : 18000
  refreshExpiration: 25000

security:
  token:
    blacklistExpiration: 3600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor




#server:
#  port: 8080
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/swsback
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  jpa:
#    #    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#        show_sql: false
#        format_sql: true
#    open-in-view: false
#
#jwt:
#  secretKey: gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767gyuhgyyg6767
#  accessExpiration: 3600000
#  refreshExpiration: 604800000
